trainer:
  max_epochs: 1
  limit_train_batches: 1
  limit_val_batches: 0
  logger: false
  enable_checkpointing: false
  enable_model_summary: false
model:
  class_path: dlt.training.lightning_module.DLTTrainingModule
  init_args:
    config:
      class_path: dlt.configuration_dlt.DLTConfig
      init_args:
        dataset_name: publaynet
        max_num_comp: 4
        categories_num: 7
        latent_dim: 32
        num_layers: 1
        num_heads: 4
        cond_emb_size: 12
        cat_emb_size: 8
        num_cont_timesteps: 4
        num_discrete_steps: 2
    optimizer_config:
      class_path: dlt.training.config.DLTOptimizerConfig
data:
  class_path: dlt.training.datamodule.DLTDataModule
  init_args:
    batch_size: 2
    length: 4
    max_num_comp: 4
    categories_num: 7
