"""Parity tests against golden data generated by executing vendor code."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import cast

import pytest
import numpy as np

from layoutprompter.parsing import Parser
from layoutprompter.selection import GenTypeExemplarSelection
from layoutprompter.serialization import build_prompt, create_serializer
from layoutprompter.vendor_parity import fixture_records


@pytest.mark.vendor_parity
def test_prompt_selection_and_parser_match_vendor_golden(tmp_path: Path) -> None:
    """Prompt bytes, selected exemplars, and parsed tensors match vendor golden."""
    if not _vendor_available():
        pytest.skip("LayoutPrompter vendor source is not available")
    golden = _generate_vendor_golden(tmp_path)
    train_data, test_data = fixture_records()

    serializer = create_serializer("webui", "gent", "seq", "seq")
    prompt = build_prompt(serializer, [train_data[2]], test_data, "webui")
    assert prompt.encode() == cast(str, golden["prompt"]).encode()

    selector = GenTypeExemplarSelection(
        train_data=train_data,
        candidate_size=-1,
        num_prompt=2,
        shuffle=False,
    )
    assert [record["id"] for record in selector(test_data)] == cast(
        list[str], golden["selection_ids"]
    )

    labels, bboxes = Parser("webui", "seq").parse_vendor_compatible(
        cast(str, golden["parser_prediction"])
    )
    assert np.array_equal(labels, np.asarray(cast(list[int], golden["parser_labels"])))
    assert np.array_equal(
        bboxes, np.asarray(cast(list[list[float]], golden["parser_bboxes"]))
    )


def _generate_vendor_golden(tmp_path: Path) -> dict[str, object]:
    output = tmp_path / "layoutprompter_vendor_golden.json"
    script = Path(__file__).parents[2] / "scripts" / "generate_vendor_golden.py"
    subprocess.run(
        [sys.executable, str(script), "--output", str(output)],
        check=True,
        cwd=Path(__file__).parents[2],
    )
    return json.loads(output.read_text(encoding="utf-8"))


def _vendor_available() -> bool:
    repo_root = Path(__file__).resolve().parents[4]
    candidates = [
        repo_root / "vendor" / "ms-layout-generation" / "LayoutPrompter" / "src",
        repo_root.parent
        / "design-generators"
        / "vendor"
        / "ms-layout-generation"
        / "LayoutPrompter"
        / "src",
    ]
    return any((candidate / "serialization.py").exists() for candidate in candidates)
