seed_everything: false
trainer:
  accelerator: auto
  devices: auto
  precision: 32
  max_epochs: 200
  check_val_every_n_epoch: 20
  num_sanity_val_steps: 2
model:
  class_path: layout_flow.training.LayoutFlowTrainingModule
  init_args:
    config:
      class_path: layout_flow.LayoutFlowConfig
      init_args:
        dataset_name: rico25
    learning_rate: 0.0005
    scheduler: reduce_on_plateau
    condition_policy: random4
    geom_l1_weight: 0.2
    seed_mode: default
    fid_calc_every_n: 20
data:
  class_path: layout_flow.training.LayoutFlowDataModule
  init_args:
    dataset_name: rico25
    data_path: .cache/layout-flow/data/rico25
    batch_size: 256
    max_length: 20
    num_workers: 4
    box_format: xywh
