"""Parity tests against goldens regenerated by executing vendor code."""

import importlib.util
import json
from pathlib import Path
from typing import Protocol, cast

import pytest

from layout_gpt.exemplars import (
    LayoutExample,
    select_fixed_random,
    select_k_similar,
)
from layout_gpt.parser import parse_3d_layout_line, parse_layout_line
from layout_gpt.prompts import form_prompt_for_chatgpt, form_prompt_for_gpt3

pytestmark = pytest.mark.vendor_parity


class GoldenBuilder(Protocol):
    """Callable exposed by the vendor golden generation script."""

    def __call__(self, vendor_root: Path | None = None) -> dict[str, object]: ...


def _vendor_root() -> Path:
    worktree_root = Path(__file__).resolve().parents[4]
    candidates = [
        worktree_root / "vendor" / "layout-gpt",
        Path(str(worktree_root).split("=", 1)[0]) / "vendor" / "layout-gpt",
    ]
    required_file = Path("dataset/NSR-1K/counting/counting.train.json")
    for candidate in candidates:
        if (candidate / required_file).exists():
            return candidate
    pytest.skip("vendor/layout-gpt is not available")


def test_prompt_and_exemplar_selection_match_vendor_generated_golden() -> None:
    golden = _build_vendor_golden()
    records = _candidate_records(golden)
    examples = [
        LayoutExample.from_vendor_record(record, setting="counting")
        for record in records
    ]
    query = str(_val_records()[0]["prompt"])

    fixed_examples = select_fixed_random(examples, k=3, seed=42)
    assert [example.id for example in fixed_examples] == golden["fixed_random_ids"]
    assert _json_bytes(
        form_prompt_for_chatgpt(
            query,
            exemplars=fixed_examples,
            canvas_size=64,
            token_counter=_byte_count,
            input_length_limit=100_000,
        )
    ) == _json_bytes(golden["fixed_chat_prompt"])
    assert (
        form_prompt_for_gpt3(
            query,
            exemplars=fixed_examples,
            canvas_size=64,
            token_counter=_byte_count,
            input_length_limit=100_000,
        ).encode()
        == str(golden["fixed_completion_prompt"]).encode()
    )

    k_examples = select_k_similar(
        examples[:4],
        query=query,
        k=3,
        query_embedding=lambda _query: (0.0, 1.0),
        example_embeddings=[
            (1.0, 0.0),
            (0.0, 1.0),
            (0.6, 0.8),
            (0.0, -1.0),
        ],
    )
    assert [example.id for example in k_examples] == golden["k_similar_ids"]
    assert (
        form_prompt_for_gpt3(
            query,
            exemplars=k_examples,
            canvas_size=64,
            token_counter=_byte_count,
            input_length_limit=100_000,
        ).encode()
        == str(golden["k_similar_completion_prompt"]).encode()
    )


def test_parser_matches_vendor_generated_golden() -> None:
    golden = _build_vendor_golden()

    parsed_2d = [
        _normalize_2d(parse_layout_line(line, canvas_size=64))
        for line in cast(list[str], golden["parser_lines"])
    ]
    assert parsed_2d == [
        _normalize_vendor_parse(item)
        for item in cast(list[object], golden["parsed_2d"])
    ]

    parsed_3d = [
        _normalize_3d(parse_3d_layout_line(line, unit="m"))
        for line in cast(list[str], golden["parser_3d_lines"])
    ]
    assert parsed_3d == [
        _normalize_vendor_3d_parse(item)
        for item in cast(list[object], golden["parsed_3d"])
    ]


def test_vendor_golden_metadata_documents_regeneration_policy() -> None:
    metadata = json.loads(
        (Path(__file__).with_name("golden_metadata.json")).read_text()
    )

    assert metadata["golden_policy"].startswith("Regenerate deterministic")
    assert metadata["seed"] == 42
    assert metadata["k"] == 3
    assert metadata["canvas_size"] == 64


def _build_vendor_golden() -> dict[str, object]:
    module_path = (
        Path(__file__).resolve().parents[2] / "scripts/generate_vendor_golden.py"
    )
    spec = importlib.util.spec_from_file_location("generate_vendor_golden", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    build_golden = cast(GoldenBuilder, getattr(module, "build_golden"))
    return build_golden(_vendor_root())


def _candidate_records(golden: dict[str, object]) -> list[dict[str, object]]:
    records = _train_records()
    metadata = cast(dict[str, object], golden["metadata"])
    ids = set(cast(list[int | str], metadata["candidate_ids"]))
    return [record for record in records if record["id"] in ids]


def _train_records() -> list[dict[str, object]]:
    return cast(
        list[dict[str, object]],
        json.loads(
            (_vendor_root() / "dataset/NSR-1K/counting/counting.train.json").read_text()
        ),
    )


def _val_records() -> list[dict[str, object]]:
    return cast(
        list[dict[str, object]],
        json.loads(
            (_vendor_root() / "dataset/NSR-1K/counting/counting.val.json").read_text()
        ),
    )


def _byte_count(text: str) -> int:
    return len(text.encode())


def _json_bytes(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def _normalize_2d(item: object) -> list[object | None]:
    if item is None:
        return [None, None]
    label = getattr(item, "label")
    bbox = [float(value) for value in getattr(item, "bbox_ltrb")]
    return [label, bbox]


def _normalize_vendor_parse(item: object) -> list[object | None]:
    item = cast(tuple[object | None, object | None], item)
    label, bbox = item
    if label is None:
        return [None, None]
    bbox = cast(list[float], bbox)
    return [label, [float(value) for value in bbox]]


def _normalize_3d(item: object) -> list[object | None]:
    if item is None:
        return [None, None]
    return [
        getattr(item, "label"),
        {
            "depth": getattr(item, "depth"),
            "height": getattr(item, "height"),
            "left": getattr(item, "left"),
            "length": getattr(item, "length"),
            "orientation": getattr(item, "orientation"),
            "top": getattr(item, "top"),
            "width": getattr(item, "width"),
        },
    ]


def _normalize_vendor_3d_parse(item: object) -> list[object | None]:
    item = cast(tuple[object | None, object | None], item)
    label, values = item
    if label is None:
        return [None, None]
    return [label, values]
