"""Generate LayoutPrompter vendor-parity golden data.

The generated JSON is intentionally not committed. Tests call this script in a
temporary directory so the golden remains reproducible from the read-only vendor
implementation.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import random
import sys
import types
from itertools import permutations
from pathlib import Path
from collections.abc import Iterable, Sequence
from typing import Final

from laygen.common.vendor import vendor_root
from layoutprompter.enums import LayoutPrompterDataset, LayoutPrompterTask, PromptFormat
from layoutprompter.vendor_parity import fixture_records, parser_prediction

_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[3]
_VENDOR_REPO: Final[str] = "ms-layout-generation"
_VENDOR_SRC: Final[Path] = Path("LayoutPrompter") / "src"
_VENDOR_SRC_MARKER: Final[Path] = Path("serialization.py")
_VENDOR_REPO_MARKER: Final[Path] = _VENDOR_SRC / _VENDOR_SRC_MARKER
_PARITY_DATASET: Final[LayoutPrompterDataset] = LayoutPrompterDataset.webui
_PARITY_TASK: Final[LayoutPrompterTask] = LayoutPrompterTask.gent
_PARITY_FORMAT: Final[PromptFormat] = PromptFormat.SEQ


def generate_golden() -> dict[str, object]:
    """Execute vendor code and return deterministic golden data."""
    _install_vendor_stubs()
    vendor_src = _vendor_src()
    sys.path.insert(0, str(vendor_src))
    try:
        vendor_parsing = importlib.import_module("parsing")
        vendor_selection = importlib.import_module("selection")
        vendor_serialization = importlib.import_module("serialization")

        train_data, test_data = fixture_records()
        serializer = getattr(vendor_serialization, "create_serializer")(
            str(_PARITY_DATASET),
            str(_PARITY_TASK),
            str(_PARITY_FORMAT),
            str(_PARITY_FORMAT),
            True,
            True,
            False,
        )
        prompt = getattr(vendor_serialization, "build_prompt")(
            serializer,
            [train_data[2]],
            test_data,
            str(_PARITY_DATASET),
        )
        selector = getattr(vendor_selection, "GenTypeExemplarSelection")(
            train_data=train_data,
            candidate_size=-1,
            num_prompt=2,
            shuffle=False,
        )
        selected = selector(test_data)
        parser = getattr(vendor_parsing, "Parser")(
            str(_PARITY_DATASET), str(_PARITY_FORMAT)
        )
        parsed_labels, parsed_bboxes = parser([parser_prediction()])[0]
    finally:
        sys.path.remove(str(vendor_src))

    return {
        "metadata": {
            "source": "vendor/ms-layout-generation/LayoutPrompter",
            "dataset": str(_PARITY_DATASET),
            "task": str(_PARITY_TASK),
            "input_format": str(_PARITY_FORMAT),
            "output_format": str(_PARITY_FORMAT),
            "seed": None,
            "notes": "Generated by executing vendor prompt/selection/parser paths before any LLM API call.",
        },
        "prompt": prompt,
        "selection_ids": [record["id"] for record in selected],
        "parser_prediction": parser_prediction(),
        "parser_labels": parsed_labels.tolist(),
        "parser_bboxes": parsed_bboxes.tolist(),
    }


def main() -> None:
    """Generate vendor golden JSON to a file or stdout."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    payload = json.dumps(generate_golden(), indent=2, sort_keys=True) + "\n"
    if args.output is None:
        print(payload, end="")
    else:
        args.output.write_text(payload, encoding="utf-8")


def _install_vendor_stubs() -> None:
    sys.modules.setdefault("clip", types.ModuleType("clip"))
    sys.modules.setdefault("cv2", types.ModuleType("cv2"))
    scipy_module = types.ModuleType("scipy")
    scipy_optimize = types.ModuleType("scipy.optimize")
    setattr(scipy_optimize, "linear_sum_assignment", _linear_sum_assignment)
    sys.modules.setdefault("scipy", scipy_module)
    sys.modules.setdefault("scipy.optimize", scipy_optimize)


def _vendor_src() -> Path:
    env_path = os.getenv("LAYOUTPROMPTER_VENDOR_SRC")
    if env_path:
        return vendor_root(
            _VENDOR_REPO,
            marker=_VENDOR_SRC_MARKER,
            path=env_path,
            repo_root=_REPO_ROOT,
        )
    return (
        vendor_root(_VENDOR_REPO, marker=_VENDOR_REPO_MARKER, repo_root=_REPO_ROOT)
        / _VENDOR_SRC
    )


def _linear_sum_assignment(
    cost_matrix: Iterable[Sequence[float]],
) -> tuple[list[int], list[int]]:
    matrix = [list(row) for row in cost_matrix]
    rows = len(matrix)
    cols = len(matrix[0]) if rows else 0
    size = min(rows, cols)
    best_score: float | None = None
    best_rows: list[int] = []
    best_cols: list[int] = []
    if rows <= cols:
        for candidate_cols in permutations(range(cols), size):
            score = sum(
                float(matrix[row][col]) for row, col in enumerate(candidate_cols)
            )
            if best_score is None or score < best_score:
                best_score = score
                best_rows = list(range(size))
                best_cols = list(candidate_cols)
    else:
        for candidate_rows in permutations(range(rows), size):
            score = sum(
                float(matrix[row][col]) for col, row in enumerate(candidate_rows)
            )
            if best_score is None or score < best_score:
                best_score = score
                best_rows = list(candidate_rows)
                best_cols = list(range(size))
    return best_rows, best_cols


if __name__ == "__main__":
    random.seed(0)
    main()
