seed_everything: false
trainer:
  accelerator: auto
  devices: auto
  precision: 32-true
  max_epochs: 300
  num_sanity_val_steps: 0
model:
  class_path: ds_gan.training.DSGANTrainingModule
  init_args:
    config:
      class_path: ds_gan.DSGANConfig
      init_args:
        dataset_name: pku_posterlayout
        backbone: resnet50
        max_elem: 32
        image_size: [350, 240]
        backbone_feature_size: 330
    generator_learning_rate: 0.0001
    discriminator_learning_rate: 0.001
    generator_backbone_learning_rate: 0.00001
    discriminator_backbone_learning_rate: 0.0001
    adversarial_weight_ramp_steps: 100
    scheduler_gamma: 0.8
    scheduler_generator_milestones: [0, 50, 100, 150, 200, 250]
    scheduler_discriminator_milestones: [0, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275]
    seed: 0
data:
  class_path: ds_gan.training.DSGANDataModule
  init_args:
    dataset_name: pku_posterlayout
    batch_size: 128
    test_batch_size: 4
    max_elem: 32
    num_workers: 16
    seed: 0
